#!/bin/bash
# Write results/jobs/<RUN_STEM>/merge_invoke.sh for merge waiter / check-partials.
# Called by slurm_binary_h128_crossvar_ablation_chain.sh; safe to re-run for recovery.

set -euo pipefail

RUN_STEM="${1:?RUN_STEM required}"
REPO="${2:-${SCRATCH:-}/ts-sandbox}"
DATE_TAG="${3:-${RUN_STEM%%-bin-h128*}}"

if [[ ! -d "$REPO" ]]; then
    REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi

JOB_DIR="$REPO/results/jobs/${RUN_STEM}"
EVAL_OUT="$REPO/results/datasets/${RUN_STEM}"
mkdir -p "$JOB_DIR"

VARIANTS=(
    exp1-datasetnorm
    exp2-tokens-only
    exp3-datasetnorm-tokens-only
    exp4-baseline-xvar
)

DATASETS=(
    ETTh1 ETTh2 exchange_rate illness weather ETTm1 ETTm2 electricity traffic dalia
)

CHECK_ARGS=(--output-dir "$EVAL_OUT")
MERGE_ARGS=(--output-dir "$EVAL_OUT")

for variant in "${VARIANTS[@]}"; do
    # Any dataset checkpoint dir works; labels drive partial filenames.
    root="$REPO/results/ckpts/${DATE_TAG}-bin-h128-xvar-${variant}-etth1"
    CHECK_ARGS+=(--variant-root "${variant}=${root}")
    MERGE_ARGS+=(--variant-root "${variant}=${root}")
done

CHECK_ARGS+=(--datasets "${DATASETS[@]}")
MERGE_ARGS+=(--datasets "${DATASETS[@]}")

{
    echo "# Generated by utils/write_crossvar_merge_invoke.sh"
    echo "EVAL_OUT=\"$EVAL_OUT\""
    echo -n "CHECK_ARGS=("
    printf ' %q' "${CHECK_ARGS[@]}"
    echo ")"
    echo -n "MERGE_ARGS=("
    printf ' %q' "${MERGE_ARGS[@]}"
    echo ")"
} > "$JOB_DIR/merge_invoke.sh"

echo "Wrote $JOB_DIR/merge_invoke.sh"
