extends: binary_anchor_stationary_flat_subsets_grad_accum_150_lr_lo.yaml

wandb:
  project: ts-sandbox-flat-ablations

experiment:
  use_window_normalization: false
  name: binary-anchor-stationary-flat-subsets-grad-accum-150-lr-lo-no-win-norm
  experiment_name: binary_anchor_stationary_flat_subsets_grad_accum_150_lr_lo_no_win_norm
