extends: binary_anchor_stationary_flat_subsets_ema099.yaml

experiment:
  name: binary-anchor-stationary-flat-subsets-ema099-lb336-hz96
  experiment_name: binary-anchor-stationary-flat-subsets-ema099-lb336-hz96
  lookback_length: 336
  forecast_length: 96
  lookback_overlap: 8
