extends: binary_anchor_ar_grad_accum_base.yaml

training:
  diffusion_effective_batch_multiplier: 4.0

experiment:
  name: binary-anchor-ar-grad-accum-400
  experiment_name: binary_anchor_ar_grad_accum_400
