extends: binary_anchor_ar.yaml

experiment:
  name: binary-anchor-ar-lb336-hz96
  experiment_name: binary_anchor_ar_lb336_hz96
  lookback_length: 336
  forecast_length: 96
  itrans_lookback_length: 336
